name: Publish npm package prerelease

on:
  workflow_dispatch:

jobs:
  prerelease:
    name: Publish npm package prerelease
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_SCOPED_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
          scope: '@calm1205'

      - name: Install dependencies
        run: npm ci

      - name: Set branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF_NAME#refs/heads/} | tr '/' '-')" >> ${{ env.GITHUB_ENV }}

      - name: Update beta version
        run: npm version prerelease --preid=${{ env.BRANCH_NAME }} --no-git-tag-version

      - name: Publish to npm
        run: npm publish --tag ${{ env.BRANCH_NAME }}
